using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]

public partial class GameStartModel
{
    [RealtimeProperty(1, true, true)]
    private bool _gameStarted;
}


/* ----- Begin Normal Autogenerated Code ----- */
public partial class GameStartModel : RealtimeModel {
    public bool gameStarted {
        get {
            return _gameStartedProperty.value;
        }
        set {
            if (_gameStartedProperty.value == value) return;
            _gameStartedProperty.value = value;
            InvalidateReliableLength();
            FireGameStartedDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(GameStartModel model, T value);
    public event PropertyChangedHandler<bool> gameStartedDidChange;
    
    public enum PropertyID : uint {
        GameStarted = 1,
    }
    
    #region Properties
    
    private ReliableProperty<bool> _gameStartedProperty;
    
    #endregion
    
    public GameStartModel() : base(null) {
        _gameStartedProperty = new ReliableProperty<bool>(1, _gameStarted);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _gameStartedProperty.UnsubscribeCallback();
    }
    
    private void FireGameStartedDidChange(bool value) {
        try {
            gameStartedDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _gameStartedProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _gameStartedProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.GameStarted: {
                    changed = _gameStartedProperty.Read(stream, context);
                    if (changed) FireGameStartedDidChange(gameStarted);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _gameStarted = gameStarted;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
