using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class InterceptorBoolModel
{
    [RealtimeProperty(1, true, true)]
    private bool _playAnimation;

}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class InterceptorBoolModel : RealtimeModel {
    public bool playAnimation {
        get {
            return _playAnimationProperty.value;
        }
        set {
            if (_playAnimationProperty.value == value) return;
            _playAnimationProperty.value = value;
            InvalidateReliableLength();
            FirePlayAnimationDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(InterceptorBoolModel model, T value);
    public event PropertyChangedHandler<bool> playAnimationDidChange;
    
    public enum PropertyID : uint {
        PlayAnimation = 1,
    }
    
    #region Properties
    
    private ReliableProperty<bool> _playAnimationProperty;
    
    #endregion
    
    public InterceptorBoolModel() : base(null) {
        _playAnimationProperty = new ReliableProperty<bool>(1, _playAnimation);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _playAnimationProperty.UnsubscribeCallback();
    }
    
    private void FirePlayAnimationDidChange(bool value) {
        try {
            playAnimationDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _playAnimationProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _playAnimationProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.PlayAnimation: {
                    changed = _playAnimationProperty.Read(stream, context);
                    if (changed) FirePlayAnimationDidChange(playAnimation);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _playAnimation = playAnimation;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
