using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;
using Normal.Realtime;

[RealtimeModel]

public partial class Points4Model
{
    [RealtimeProperty(1, true, true)]
    private int _player4Points;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class Points4Model : RealtimeModel {
    public int player4Points {
        get {
            return _player4PointsProperty.value;
        }
        set {
            if (_player4PointsProperty.value == value) return;
            _player4PointsProperty.value = value;
            InvalidateReliableLength();
            FirePlayer4PointsDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(Points4Model model, T value);
    public event PropertyChangedHandler<int> player4PointsDidChange;
    
    public enum PropertyID : uint {
        Player4Points = 1,
    }
    
    #region Properties
    
    private ReliableProperty<int> _player4PointsProperty;
    
    #endregion
    
    public Points4Model() : base(null) {
        _player4PointsProperty = new ReliableProperty<int>(1, _player4Points);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _player4PointsProperty.UnsubscribeCallback();
    }
    
    private void FirePlayer4PointsDidChange(int value) {
        try {
            player4PointsDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _player4PointsProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _player4PointsProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Player4Points: {
                    changed = _player4PointsProperty.Read(stream, context);
                    if (changed) FirePlayer4PointsDidChange(player4Points);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _player4Points = player4Points;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
