using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;
using Normal.Realtime;

[RealtimeModel]

public partial class Points3Model
{
    [RealtimeProperty(1, true, true)]
    private int _player3Points;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class Points3Model : RealtimeModel {
    public int player3Points {
        get {
            return _player3PointsProperty.value;
        }
        set {
            if (_player3PointsProperty.value == value) return;
            _player3PointsProperty.value = value;
            InvalidateReliableLength();
            FirePlayer3PointsDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(Points3Model model, T value);
    public event PropertyChangedHandler<int> player3PointsDidChange;
    
    public enum PropertyID : uint {
        Player3Points = 1,
    }
    
    #region Properties
    
    private ReliableProperty<int> _player3PointsProperty;
    
    #endregion
    
    public Points3Model() : base(null) {
        _player3PointsProperty = new ReliableProperty<int>(1, _player3Points);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _player3PointsProperty.UnsubscribeCallback();
    }
    
    private void FirePlayer3PointsDidChange(int value) {
        try {
            player3PointsDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _player3PointsProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _player3PointsProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Player3Points: {
                    changed = _player3PointsProperty.Read(stream, context);
                    if (changed) FirePlayer3PointsDidChange(player3Points);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _player3Points = player3Points;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
