using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;


[RealtimeModel]
public partial class CubeScaleModel
{
    [RealtimeProperty(1, true, true)]
    private Vector3 _scale;

}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class CubeScaleModel : RealtimeModel {
    public UnityEngine.Vector3 scale {
        get {
            return _scaleProperty.value;
        }
        set {
            if (_scaleProperty.value == value) return;
            _scaleProperty.value = value;
            InvalidateReliableLength();
            FireScaleDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(CubeScaleModel model, T value);
    public event PropertyChangedHandler<UnityEngine.Vector3> scaleDidChange;
    
    public enum PropertyID : uint {
        Scale = 1,
    }
    
    #region Properties
    
    private ReliableProperty<UnityEngine.Vector3> _scaleProperty;
    
    #endregion
    
    public CubeScaleModel() : base(null) {
        _scaleProperty = new ReliableProperty<UnityEngine.Vector3>(1, _scale);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _scaleProperty.UnsubscribeCallback();
    }
    
    private void FireScaleDidChange(UnityEngine.Vector3 value) {
        try {
            scaleDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _scaleProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _scaleProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Scale: {
                    changed = _scaleProperty.Read(stream, context);
                    if (changed) FireScaleDidChange(scale);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _scale = scale;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
